<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <ApplicationIcon>diskusage.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DiskUsage.Cli\**;DiskUsage.Core\**" />
    <EmbeddedResource Remove="DiskUsage.Cli\**;DiskUsage.Core\**" />
    <None Remove="DiskUsage.Cli\**;DiskUsage.Core\**" />
    <Page Remove="DiskUsage.Cli\**;DiskUsage.Core\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="folder.png" />
    <None Remove="diskusage.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="folder.png" />
    <Resource Include="diskusage.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="DiskUsage.Core\DiskUsage.Core.csproj" />
  </ItemGroup>

</Project>
